WarsawUM.Threats/ViewModels/ErrorViewModel.cs
using System;

namespace WarsawUM.Threats.ViewModels
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WarsawUM.Threats/ViewModels/NotificationViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WarsawUM.Threats.ViewModels
{
    public class NotificationViewModel
    {
        public string District { get; set; }

        public string Event { get; set; }

        public DateTime CreateDate { get; set; }

        public string Street { get; set; }

        public string Status { get; set; }

        public DateTime StatusDate { get; set; }
    }
}

WarsawUM.Threats/ViewModels/NotificationsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WarsawUM.Threats.ViewModels
{
    public class NotificationsViewModel
    {
        public IEnumerable<NotificationViewModel> Notifications { get; set; }
    }
}

WarsawUM.Threats/ViewModels/Profiles/NotificationProfile.cs
using AutoMapper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WarsawUM.Api.Models;

namespace WarsawUM.Threats.ViewModels.Profiles
{
    public class NotificationProfile : Profile
    {
        public NotificationProfile()
        {
            CreateMap<Notification, NotificationViewModel>()
                .ForMember(dest => dest.Status, opt =>
                {
                    opt.MapFrom(src => src.Statuses.Last().Status);
                })
                .ForMember(dest => dest.StatusDate, opt =>
                {
                    opt.MapFrom(src =>
                        DateTimeOffset.FromUnixTimeMilliseconds(src.Statuses.Last().ChangeDate).UtcDateTime);
                })
                .ForMember(dest => dest.CreateDate, opt =>
                {
                    opt.MapFrom(src => DateTimeOffset.FromUnixTimeMilliseconds(src.CreateDate).UtcDateTime);
                });
        }
    }
}

WarsawUM.Threats/Controllers/NotificationController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using WarsawUM.Api.Interfaces;
using WarsawUM.Api.Models;
using WarsawUM.Threats.ViewModels;

namespace WarsawUM.Threats.Controllers
{
    public class NotificationController : Controller
    {
        private readonly INotificationsRepository _notificationRepository;
        private readonly IMapper _mapper;

        public NotificationController(INotificationsRepository notificationRepository, IMapper mapper)
        {
            _notificationRepository = notificationRepository;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            var rawNotifications = await _notificationRepository.GetNotifications(1);
            NotificationsViewModel viewModel = new NotificationsViewModel()
            {
                Notifications = _mapper.Map<IEnumerable<Notification>, IEnumerable<NotificationViewModel>>(rawNotifications)
                                       .OrderByDescending(x => x.CreateDate)
            };
            return View(viewModel);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WarsawUM.Threats/Views/Notification/Index.cshtml
@model WarsawUM.Threats.ViewModels.NotificationsViewModel
@{
    ViewData["Title"] = "Notifications";
}
<br />
<h4>Data from last 24 hours</h4>
<br/>
<table class="table table-hover table-dark">
    <thead>
        <tr>
            <th scope="col">District</th>
            <th scope="col">Event</th>
            <th scope="col">CreationDate</th>
            <th scope="col">Street</th>
            <th scope="col">Status</th>
            <th scope="col">StatusDate</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var notification in Model.Notifications)
        {
            <tr>
                <td>@(notification.District)</td>
                <td>@(notification.Event)</td>
                <td>@(notification.CreateDate)</td>
                <td>@(notification.Street)</td>
                <td>@(notification.Status)</td>
                <td>@(notification.StatusDate)</td>
            </tr>
        }
    </tbody>
</table>

WarsawUM.Threats/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - 19115 Warsaw</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <a asp-area="" asp-controller="Notification" asp-action="Index" class="navbar-brand">Warsaw Notification System - 19115</a>
            </div>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>